---
title: "Exercise 03-B Solution"
author: "(fill in your name)"
output:
  html_document:
    df_print: kable
    theme: simplex
    toc: true
    urlcolor: blue
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages(tvm)
library(tvm)
```

## Exercise Directions

This file contains an exercise.  Please read the text and adjust the necessary code chunks (between \`\`\` symbols), to accomplish the stated goal.

## Bond Portfolio

### Loan Bond Portfolio

Find the csv file for the Bond Portfolio in the data directory and load

```{r BondPortfolio}

my_file       <- "../data/iShares-US-Treasury-Bond-ETF_fund.csv"
bondPortfolio <- read.csv(my_file, stringsAsFactors = FALSE)

head(bondPortfolio)

```


### Sum Market Value

What is the market value of the portfolio in millions

```{r MarketValue}

mvMil <- sum(bondPortfolio$Market.Value)/1000000

print(mvMil)
```


## Session Info

```{r}
devtools::session_info()
```

```{r}
date()
sessionInfo()
```

```{r}
date()
Sys.getenv()
```


