
---
title: "Residual Minimal Working Example (MWE)"
author: "Larry Tentor"
date: "`r (Sys.Date())`"
output:
  html_document:
    df_print: kable
    theme: simplex
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    urlcolor: blue
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Motivation

We have selected to model a linear relationship and we wish to examine the residuals.

## Data

```{r DataSample}
## 
dataSample <- read.csv(text= "
Name,Score,Dependent
Larry,3,8
Bert,7,50
William,5,25
Sri,5,26
Meredith,6,33
Evan,8,60
Rich,4,15
Arundel,7,46
Theo,2,5",stringsAsFactor=FALSE)

```


## Exploratory Graph 

```{r ExploratoryGraph}
p <- ggplot() + 
     geom_point(data = dataSample, aes(x = Score, y = Dependent), color = "blue") +
     xlab("Score") +
     ylab("Dependent") +
     ggtitle("Sample Graph") 

print(p)

```

## Estimate Linear Model

```{r Estimate}

simple.fit          <- lm(Dependent~Score, data=dataSample)

class(simple.fit)
simple.fit
dataSample$residuals <- simple.fit$residuals
dataSample$fit       <- simple.fit$fitted.values
```

## Examine Curve Fit


```{r}
p <- ggplot() + 
     geom_point(data = dataSample, aes(x = Score, y = Dependent), color = "blue") +
     geom_line(data = dataSample, aes(x = Score, y = fit), color = "red") +
     xlab('Score') +
     ylab('Dependent') +
     ggtitle("Curve Fit") 

print(p)

```

## Examine Residuals

Do these residuals appear to be random?

If they are not random noise, then maybe we missed a modeling term...

```{r}
p <- ggplot() + 
     geom_point(data = dataSample, aes(x = Score, y = residuals), color = "green") +
     xlab('Score') +
     ylab('Dependent') +
     ggtitle("Curve Fit") 

print(p)

```

