---
title:  "Security Exchange Commission"
author: "Larry Tentor"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, metropolis, metropolis-fonts]
#    css: ["metropolis"]
#    css: "presentation.css"
    nature:
      highlightLines: true
      highlightStyle: solarized-dark
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
#output: ioslides_presentation
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

class: inverse, mline, center, middle

# Attribution

McGraw Hill has provided power point slides that were substantially used to construct this R Markdown deck.

---

class: inverse, mline, center, middle
# Federal Reserve Activity Update

???
There has been tremendous activity at the Federal Reserve Bank during March to have an economic response to the onset of COVID-19 pandemic.  This is an update from last week.

---
# Federal Reserve Update March 2020 .font50[1]

[Press Releases (suggested filter for ☑ Monetary Policy) ](https://www.federalreserve.gov/newsevents/pressreleases.htm)
- [Federal Reserve Action, March 31](https://www.federalreserve.gov/newsevents/pressreleases/monetary20200331a.htm "FIMA Repo")
    - The Federal Reserve on Tuesday announced the establishment of a temporary **repurchase agreement facility for foreign and international monetary authorities (FIMA Repo Facility)** to help support the smooth functioning of financial markets, including the U.S. Treasury market, and thus maintain the supply of credit to U.S. households and businesses. The FIMA Repo Facility will allow FIMA account holders, which consist of central banks and other international monetary authorities with accounts at the Federal Reserve Bank of New York, to enter into repurchase agreements with the Federal Reserve. In these transactions, FIMA account holders temporarily exchange their U.S. Treasury securities held with the Federal Reserve for U.S. dollars, which can then be made available to institutions in their jurisdictions. This facility should help support the smooth functioning of the U.S. Treasury market by **providing an alternative temporary source of U.S. dollars other than sales of securities** in the open market. It should also serve, along with the U.S. dollar liquidity swap lines the Federal Reserve has established with other central banks, to help ease strains in global U.S. dollar funding markets.

☒ Federal Reserve Activity Update on 31 March 2020

---
# Security Exchange Commission

.pull-left[
- Introduction
- Creation of SEC
- Organization of SEC
- Laws the Govern the Industry
- Data of the SEC
]

---
class: inverse, mline, center, middle
# SEC Introduction

---
# SEC Introduction

## Mission and Vision
Source: [SEC What We Do](https://www.sec.gov/Article/whatwedo.html)

- **Mission** of the U.S. Securities and Exchange Commission is to 
    - **protect investors**, 
    - **maintain fair, orderly, and efficient markets**, and
    - **facilitate capital formation**.
- As our nation's securities exchanges mature into global for-profit competitors, there is even greater need for **sound market regulation**.
- And the common interest of all Americans in a
    - growing economy that produces jobs,
    - improves our standard of living, and 
    - protects the value of our savings 
    - means that all of the SEC's actions must be taken with an eye toward promoting the capital formation that is necessary to sustain economic growth.

---
# SEC Introduction

- The laws and rules that govern the securities industry in the United States derive from a **simple and straightforward concept**: all investors, whether large institutions or private individuals, should have access to certain basic facts about an investment prior to buying it, and so long as they hold it. To achieve this, the SEC requires public companies to **disclose meaningful financial and other information to the public.** 
- This provides a common pool of knowledge for all investors to use to judge for themselves whether to buy, sell, or hold a particular security. Only through the **steady flow of timely, comprehensive, and accurate information can people make sound investment decisions**.
- The result of this information flow is a **far more active, efficient, and transparent capital market that facilitates the capital formation** so important to our nation's economy.
- The SEC oversees the key participants in the securities world, including 
    - **securities exchanges**, 
    - **securities brokers and dealers**,
    - **investment advisors**, and 
    - **mutual funds**. 
    - Here the SEC is concerned primarily with promoting the disclosure of important market-related information, maintaining fair dealing, and protecting against fraud.

---
# SEC Introduction

- One of the major sources of information on which the SEC relies to bring enforcement action is investors themselves — another reason that educated and careful investors are so critical to the functioning of efficient markets. To help support investor education, the SEC offers the public a wealth of educational information on this Internet website, which also includes the **EDGAR database of disclosure documents that public companies are required to file** with the Commission.
- Though it is the primary overseer and regulator of the U.S. securities markets, the SEC works closely with many other institutions, including 
    - Congress, 
    - other federal departments and agencies,
    - the self-regulatory organizations (e.g. the stock exchanges),
    - state securities regulators, and 
    - various private sector organizations.

---
class: inverse
# Zoom Poll: SEC Mission

---
class: inverse, mline, center, middle
# SEC Creation

---
# SEC Creation

- **Setting**: After the Great Crash of 1929, public confidence in the markets plummeted, a consensus that for the economy to recover, the public's faith in the capital markets needed to be restored. Congress held hearings to identify the problems and search for solutions.
- **Result**: After these hearding, the Security Act of 1933 was passed and the followed year saw the Security Exchange Act of 1934, which created the SEC.
- **Goal**: Designed to restore investor confidence in our capital markets by providing investors and the markets with more **reliable information** and **clear rules of honest dealing**. The main purposes of these laws can be reduced to two common-sense notions:
    - Companies publicly offering securities for investment dollars **must tell the public the truth** about their businesses, the securities they are selling, and the risks involved in investing.
    - People who sell and trade securities – brokers, dealers, and exchanges – must treat investors **fairly and honestly, putting investors' interests** first.

---
class: inverse
# Zoom Poll: SEC Creation

---
class: inverse, mline, center, middle
# SEC Organization

---
# SEC Organization

- **Five (5) presidentially-appointed Commissioners**, with staggered five-year terms, see [SEC Organization Chart](https://www.sec.gov/about/secorg.pdf).  By law, no more than three of the Commissioners may belong to the same political party, ensuring non-partisanship. 
- The agency's functional responsibilities are organized into five Divisions and 24 Offices, each of which is headquartered in Washington, DC. The Commission's approximately 4,600 staff are located in Washington and in 11 Regional Offices throughout the country.
- Responsibility of the Commission to:
    - **interpret** and **enforce** federal securities laws;
    - **issue** new rules and **amend** existing rules;
    - oversee the **inspection** of securities firms, brokers, investment advisers, and ratings agencies;
    - **oversee** private regulatory organizations in the securities, accounting, and auditing fields; and
    - **coordinate** U.S. securities regulation with federal, state, and foreign authorities.

---
# SEC Organization

## Divisions
- Division of Corporation Finance
    - Oversee corporate disclosure of important information to the investing public.
- Division of Trading and Markets
    - Maintaining fair, orderly, and efficient markets.
- Division of Investment Management
    - Promotes investor protection and for promoting capital formation
- Division of Enforcement
    - Executing its law enforcement function
- Division of Economic and Risk Analysis
    - Executing its mission to protect investors, maintain fair, orderly, and efficient markets, and facilitate capital formation by integrating robust economic analysis and rigorous data analytics
- Offices

---
# SEC Organization

## Division of Corporation Finance
- Oversee corporate disclosure of important information to the investing public.
- Reviews filings by publicly-held companies
    - registration statements for newly-offered securities;
    - annual and quarterly filings (Forms 10-K and 10-Q);
    - proxy materials sent to shareholders before an annual meeting;
    - annual reports to shareholders;
    - documents concerning tender offers (a tender offer is an offer to buy a large number of shares of a corporation, usually at a premium above the current market price); and
    - filings related to mergers and acquisitions.
- Works closly with Financial Accounting Standards Board (FASB), that result in the formulation of generally accepted accounting principles (GAAP)
- Rule Making (e.g. Prosper)
    - Concept Release
    - Rule Proposal
    - Rule Adoption
    
---
# SEC Organization

## Division of Trading and Markets
- Maintaining fair, orderly, and efficient markets.
- carrying out the Commission's financial integrity program for broker-dealers;
reviewing (and in some cases approving, under authority delegated from the Commission) proposed new rules and proposed changes to existing rules filed by the SROs;
assisting the Commission in establishing rules and issuing interpretations on matters affecting the operation of the securities markets; and
surveilling the markets.

---
# SEC Organization

## Division of Investment Management
- Promotes investor protection and for promoting capital formation
- ensuring that disclosures about these investments are useful to retail customers, and that the regulatory costs which consumers must bear are not excessive.
- assisting the Commission in interpreting laws and regulations for the public and SEC inspection and enforcement staff;
- responding to no-action requests and requests for exemptive relief;
reviewing investment company and investment adviser filings;
- assisting the Commission in enforcement matters involving investment companies and advisers; and
- advising the Commission on adapting SEC rules to new circumstances.

---
# SEC Organization

## Division of Enforcement
- Recommending the commencement of investigations of securities law violations, by recommending that the Commission bring 
- civil actions in federal court or as administrative proceedings before an administrative law judge, and by
- prosecuting these cases on behalf of the Commission. 
- As an adjunct to the SEC's civil enforcement authority, the Division works closely with law enforcement agencies in the U.S. and around the world to bring criminal cases when appropriate.

???

Civil Actions: US District Court
Administrative Action

---
# SEC Organization

## Division of Economic and Risk Analysis
- Executing its mission to protect investors, maintain fair, orderly, and efficient markets, and facilitate capital formation by integrating robust economic analysis and rigorous data analytics
- Analyzing the potential economic effects of Commission rulemakings or other Commission actions. In this role, offices within DERA works closely with the other Divisions and Offices to help examine the need for regulatory action, analyze the potential economic effects of rules and other Commission actions, develop data-driven analyses of market activity, and assist in evaluating public comments and studies.
- Providing quantitative and qualitative research and support related to risk assessment. DERA staff help the Commission to anticipate, identify, and manage risks, focusing on early identification of potential fraud and illegal or questionable activities. Staff collects, analyzes, and disseminates information to the Commission and its Staff about regulated entities and market activity.
- Assisting the Division of Enforcement by, for example, providing economic and quantitative analysis and support in enforcement proceedings and settlement negotiations.

---
# SEC Organization

## Offices
- Office of the General Counsel
- Office of the Chief Accountant
- Office of Compliance Inspections and Examinations
- Office of Credit Ratings (Created by Dodd-Frank Act, July 2010)
- Office of International Affairs
- Office of Investor Education and Advocacy
- Office of Municipal Securities
- Office of Ethics Counsel
- Office of the Investor Advocate
- Office of Women and Minority Inclusion
- Office of the Chief Operating Officer
    - EDGAR Business Office
- Office of Legislative and Intergovernmental Affairs
- Office of Public Affairs
- Office of the Secretary
---
# SEC Organization

## Offices, continued
- Office of Equal Employment Opportunity
- Office of the Inspector General
- Office of Administrative Law Judges
- Office of the Advocate for Small Business Capital Formation

---
# Zoom Breakout Room

- I am about to assign a problem for you.
- I will send you to breakout rooms for five minutes.
- **You might need to reference the presention in your own session**.
- You should do problem individually.
- Then you may discuss and compare answer.
- I will stop in a couple of breakout rooms.

---
class: inverse
# Problem A

You buy a stock for $50 per share and sell it for $53 after holding it for slightly over a year and collecting a $2.00 per share dividend. Your ordinary income tax rate is 28 percent and your capital gains tax rate is 20 percent. Your after-tax rate of return is ___________________.

---
class: inverse
# Answer A

.font150[.center[
$r_t = \frac{P_t-P_{t-1}}{P_{t-1}}×(1-T_{cg})+\frac{D_t}{P_{t-1}}×(1-T_{div})$
]]

$r_t = \frac{53-50}{50}×(1-0.20)+\frac{2.00}{50}×(1-0.28)$
$r_t = 0.048 + 0.0288$
$r_t = 0.0768 = 7.68\%$

---

## Two Things

On a sheet of paper write down two things that you learned this week.

--

Breakout Room and share.

---