---
title:  "Investment Companies"
author: "Larry Tentor"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, metropolis, metropolis-fonts]
#    css: ["metropolis"]
#    css: "presentation.css"
    nature:
      highlightLines: true
      highlightStyle: solarized-dark
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
#output: ioslides_presentation
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

class: inverse, mline, center, middle

# Attribution

McGraw Hill has provided power point slides that were substantially used to construct this R Markdown deck.

---
class: inverse, mline, center, middle
# Investment Companies

---
# Investment Companies

See Power Point

---

---
# Zoom Breakout Room

- I am about to assign a problem for you.
- I will send you to breakout rooms for five minutes.
- **You might need to reference the presention in your own session**.
- You should do problem individually.
- Then you may discuss and compare answer.
- I will stop in a couple of breakout rooms.

---
class: inverse
# Problem Breakout A

.font150[[17-Q2.](./answer11.html#3) What benefits do mutual funds have for individual investors?]

.font150[[17-Q9.](./answer11.html#4) What is the difference between an open-end mutual fund and a closed-end fund?]

---
class: inverse
# Problem Breakout B

17-P2. Open-end Fund A has 165 shares of ATT valued at $35 each and 30 shares of Toro valued at $75 each. Closed-end Fund B has 75 shares of ATT and 72 shares of Toro. Both funds have 1,000 shares outstanding.

- [a.](./answer11.html#6) What is the NAV of each fund using these prices?
- [b.](./answer11.html#7) If the price of ATT stock increases to $36.25 and the price of Toro stock declines to $72.292, how does that impact the NAV of both funds?
- [c.](./answer11.html#8) Assume that another 155 shares of ATT valued at $35 are added to Fund A. The funds needed to buy the new shares are obtained by selling 676 more shares in Fund A. What is the effect on Fund A’s NAV if the prices remain unchanged from the original prices?


---
class: inverse
# Problem Breakout C

.font150[[17-Q12.](./answer11.html#9) What are the three components of the return that an investor receives from a mutual fund?]

.font150[[17-Q14.](./answer11.html#10) How might an individual’s preference for a mutual fund’s objective change over time?]

.font150[[17-Q21.](./answer11.html#11) What is a hedge fund and how is it different from a mutual fund?]

---
class: inverse
# Problem Breakout D

[17-P7.](./answer11.html#13) Suppose an individual invests $10,000 in a load mutual fund for two years. The load fee entails an up-front commission charge of 4 percent of the amount invested and is deducted from the original funds invested. In addition, annual fund operating expenses (or 12b-1 fees) are 0.85 percent. The annual fees are charged on the average net asset value invested in the fund and are recorded at the end of each year. Investments in the fund return 5 percent each year paid on the last day of the year. If the investor reinvests the annual returns paid on the investment, calculate the annual return on the mutual fund over the two-year investment period. 

---
class: inverse
# Problem Breakout E

Go to the Investment Company Institute website and find the latest information available for Total Net Assets, Number of Funds, and Number of Shareholder Accounts in U.S. mutual funds. Go to the Investment Company Institute website at [www.ici.org](www.ici.org). Click on “Research & Statistics.” Click on “Fact Books.” Click on the most recent year “20XX Investment Company Fact Book.” This will download a file onto your computer that will contain the most recent information on U.S. mutual funds. In the Data Tables of the Fact Book, go to the table listing Industry Total Net Assets, Number of Funds, Number of Share Classes, and Number of Shareholder Accounts.

Questions

- What is the most recent value for Total Net Assets and Number of Funds?

- How has each of these changed since 2016 as reported in Table 17–1?

Two Things

- On a sheet of paper write down two things that you learned this week.
- Submit this in Blackboard assignments

---
class: inverse
# Problem Breakout F

Go to the Securities Industry and Financial Markets Association website at [www.sifma.org](www.sifma.org) and find the most recent data on U.S. corporate underwriting activity using the following steps. Search for “SIFMA Fact Book.”  Select the Capital Markets Fact Book, 2019 .

Questions

- What is the most recent level of total U.S. underwriting activity?

- What is the distribution of underwriting by type of security underwritten (e.g., straight corporate debt, convertible debt, etc.)?

---
